version: '3.7'

networks:
  app-network: 
    driver: bridge

services:
  npm: 
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: 'nodecourse2-node'
    ports:
      - "3000:3000"
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network